---
- hosts: localserver
  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install SNMP packages
      apt:
        name: 
          - snmp
